package com.whisperonnx;

import android.Manifest;
import android.content.Context;
import android.os.SystemClock;
import android.widget.EditText;

import androidx.test.core.app.ActivityScenario;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import androidx.test.rule.GrantPermissionRule;

import com.whisperonnx.asr.RecordBuffer;
import com.whisperonnx.asr.Recorder;

import org.junit.After;
import org.junit.Assume;
import org.junit.BeforeClass;
import org.junit.ClassRule;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.Arrays;
import java.util.concurrent.atomic.AtomicReference;

import static org.junit.Assert.assertTrue;

/**
 * Full end-to-end transcription test.
 *
 * <p><b>Prerequisites</b> (run once before executing this test class):
 * <pre>
 *   scripts/setup_e2e_tests.sh
 * </pre>
 * That script:
 * <ol>
 *   <li>Downloads the {@code whisper_small_int8} model and pushes the 6 ONNX files
 *       to the emulator at the path the app reads them from
 *       ({@code /sdcard/Android/data/org.woheller69.whisperplus/files/}).</li>
 *   <li>Generates a short speech WAV using espeak-ng + ffmpeg and places it in
 *       {@code app/src/androidTest/assets/speech_test.wav} (packaged into the test APK).</li>
 * </ol>
 *
 * <p><b>Audio pipeline exercised by this test:</b>
 * <pre>
 *   Recorder.sTestAudioBytes (speech PCM)
 *       → RecordBuffer
 *       → Whisper ONNX (real model, real inference)
 *       → MainActivity.tvResult
 * </pre>
 *
 * <p>If either prerequisite is absent the test is <em>skipped</em> (not failed) via
 * {@link Assume}, so the rest of the suite remains green during development.
 *
 * <p>Run this test class in isolation with:
 * <pre>
 *   ./gradlew connectedDebugAndroidTest \
 *       -Pandroid.testInstrumentationRunnerArguments.class=com.whisperonnx.FullTranscriptionTest
 * </pre>
 */
@RunWith(AndroidJUnit4.class)
public class FullTranscriptionTest {

    /**
     * Phrase spoken in {@code speech_test.wav} (generated by {@code setup_e2e_tests.sh}).
     * Whisper may add punctuation or capitalise, so we check for individual words.
     */
    private static final String SPEECH_ASSET = "speech_test.wav";

    /** Allow up to 90 seconds for Whisper model inference on the emulator. */
    private static final long TRANSCRIPTION_TIMEOUT_MS = 90_000;

    @ClassRule
    public static final GrantPermissionRule grantPermissions = GrantPermissionRule.grant(
            Manifest.permission.RECORD_AUDIO,
            Manifest.permission.POST_NOTIFICATIONS
    );

    @BeforeClass
    public static void setUpEnvironment() {
        // Stage model files and enable WhisperIME using the real production code
        // paths — no bypass flags in production code.
        E2ETestHelper.setUp();
    }

    @After
    public void clearTestAudio() {
        Recorder.sTestAudioBytes = null;
    }

    // -----------------------------------------------------------------------
    // Test
    // -----------------------------------------------------------------------

    @Test
    public void speechWav_isTranscribedByWhisper_toExpectedText() throws Exception {
        Context testContext = InstrumentationRegistry.getInstrumentation().getContext();
        Context appContext  = InstrumentationRegistry.getInstrumentation().getTargetContext();

        // --- Guard: skip gracefully when prerequisites have not been set up ---
        Assume.assumeTrue(
                "Speech asset '" + SPEECH_ASSET + "' not found in androidTest/assets/. "
                + "Run scripts/setup_e2e_tests.sh first.",
                assetExists(testContext, SPEECH_ASSET)
        );
        Assume.assumeTrue(
                "Whisper model files not found in app's external files dir. "
                + "Run scripts/setup_e2e_tests.sh first.",
                modelFilesPresent(appContext)
        );

        // --- Load WAV asset; locate the 'data' sub-chunk → raw s16le PCM ---
        byte[] pcmBytes = loadWavAssetAsPcm(testContext, SPEECH_ASSET);
        assertTrue(
                "PCM payload from " + SPEECH_ASSET + " is below the 6400-byte minimum "
                + "required by Recorder (got " + pcmBytes.length + " bytes). "
                + "Regenerate the asset with scripts/setup_e2e_tests.sh.",
                pcmBytes.length >= 6400
        );

        // --- Arm the audio-injection bypass before launching the activity ---
        Recorder.sTestAudioBytes = pcmBytes;

        // Launch the activity (flags already set in @BeforeClass).
        // Use try-with-resources so the activity is always torn down cleanly.
        try (ActivityScenario<MainActivity> scenario =
                     ActivityScenario.launch(MainActivity.class)) {
            E2ETestHelper.dismissStartupDialogs();

            // Press the record button: ACTION_DOWN triggers Recorder.start(),
            // the worker thread fires the sTestAudioBytes bypass almost instantly,
            // sets RecordBuffer, and fires MSG_RECORDING_DONE.
            // ACTION_UP calls stopRecording() which unblocks via fileSavedLock.
            // MainActivity's RecorderListener then calls mWhisper.start(), which
            // wakes the threadProcessRecordBuffer for real ONNX inference.
            androidx.test.espresso.Espresso.onView(
                    androidx.test.espresso.matcher.ViewMatchers.withId(R.id.btnRecord))
                    .perform(androidx.test.espresso.action.ViewActions.click());

            // --- Poll tvResult until Whisper delivers the transcription ---
            String result = pollForTranscription(scenario, TRANSCRIPTION_TIMEOUT_MS);

            assertTrue(
                    "Transcription timed out or was empty after "
                    + (TRANSCRIPTION_TIMEOUT_MS / 1000) + "s. "
                    + "Check logcat for Whisper/Recognizer errors.",
                    !result.isEmpty()
            );

            // Whisper may add punctuation, vary capitalisation, or contract numbers.
            // Accept the result if it contains ANY of the expected words.
            String lower = result.toLowerCase();
            boolean containsExpectedWords =
                    lower.contains("one")   || lower.contains("two")  ||
                    lower.contains("three") || lower.contains("four") ||
                    lower.contains("five")  ||
                    // Whisper sometimes renders digits instead of words
                    lower.contains("1") || lower.contains("2") || lower.contains("3") ||
                    lower.contains("4") || lower.contains("5");

            assertTrue(
                    "Expected transcription to contain at least one of the words "
                    + "\"one two three four five\" (or their digit equivalents) "
                    + "but got: \"" + result + "\"",
                    containsExpectedWords
            );
        }
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    /** Returns true if {@code name} exists in the instrumentation (androidTest) assets. */
    private static boolean assetExists(Context testContext, String name) {
        try (InputStream ignored = testContext.getAssets().open(name)) {
            return true;
        } catch (IOException e) {
            return false;
        }
    }

    /**
     * Returns true if exactly 6 files are present in the app's external files dir
     * (the directory Whisper.java checks when deciding whether to launch SetupActivity).
     */
    private static boolean modelFilesPresent(Context appContext) {
        File dir = appContext.getExternalFilesDir(null);
        if (dir == null || !dir.exists()) return false;
        File[] files = dir.listFiles();
        if (files == null) return false;
        int count = 0;
        for (File f : files) {
            if (f.isFile()) count++;
        }
        return count == 6;
    }

    /**
     * Reads a WAV asset from the androidTest APK, locates the {@code data} sub-chunk,
     * and returns the raw PCM bytes (stripping all WAV headers / metadata chunks).
     *
     * <p>This approach is more robust than blindly skipping a fixed 44-byte header
     * because espeak-ng / ffmpeg can sometimes write additional metadata chunks
     * before the {@code data} chunk.
     */
    private static byte[] loadWavAssetAsPcm(Context testContext, String assetName)
            throws IOException {
        byte[] all;
        try (InputStream is = testContext.getAssets().open(assetName)) {
            all = readFully(is);
        }

        // Walk the RIFF chunk list to find the 'data' sub-chunk.
        // Layout: "RIFF" (4) + file-size (4) + "WAVE" (4), then sub-chunks:
        //   each sub-chunk: id (4) + size (4) + data (size bytes, padded to even).
        if (all.length < 12 || !startsWith(all, 0, "RIFF") || !startsWith(all, 8, "WAVE")) {
            throw new IllegalArgumentException(assetName + " is not a valid RIFF/WAVE file");
        }

        int pos = 12; // skip "RIFF" size "WAVE"
        while (pos + 8 <= all.length) {
            String chunkId = new String(all, pos, 4);
            int chunkSize = readInt32LE(all, pos + 4);
            pos += 8;
            if ("data".equals(chunkId)) {
                int dataLen = Math.min(chunkSize, all.length - pos);
                return Arrays.copyOfRange(all, pos, pos + dataLen);
            }
            // Skip this chunk (round up to even byte boundary)
            pos += chunkSize + (chunkSize & 1);
        }
        throw new IllegalArgumentException("No 'data' chunk found in " + assetName);
    }

    /** Reads all bytes from an InputStream without relying on API-33+ readAllBytes(). */
    private static byte[] readFully(InputStream is) throws IOException {
        ByteArrayOutputStream buf = new ByteArrayOutputStream();
        byte[] chunk = new byte[8192];
        int n;
        while ((n = is.read(chunk)) != -1) {
            buf.write(chunk, 0, n);
        }
        return buf.toByteArray();
    }

    private static boolean startsWith(byte[] data, int offset, String text) {
        if (offset + text.length() > data.length) return false;
        for (int i = 0; i < text.length(); i++) {
            if (data[offset + i] != (byte) text.charAt(i)) return false;
        }
        return true;
    }

    private static int readInt32LE(byte[] data, int offset) {
        return (data[offset] & 0xFF)
                | ((data[offset + 1] & 0xFF) << 8)
                | ((data[offset + 2] & 0xFF) << 16)
                | ((data[offset + 3] & 0xFF) << 24);
    }

    /**
     * Polls {@code tvResult} (an EditText) every 500 ms until it is non-empty
     * or {@code timeoutMs} has elapsed.
     *
     * @return the trimmed text, or an empty string if the timeout was reached.
     */
    private static String pollForTranscription(
            ActivityScenario<MainActivity> scenario, long timeoutMs) {
        long deadline = SystemClock.uptimeMillis() + timeoutMs;
        AtomicReference<String> text = new AtomicReference<>("");
        while (SystemClock.uptimeMillis() < deadline) {
            SystemClock.sleep(500);
            scenario.onActivity(activity -> {
                EditText tv = activity.findViewById(R.id.tvResult);
                if (tv != null) text.set(tv.getText().toString().trim());
            });
            if (!text.get().isEmpty()) break;
        }
        return text.get();
    }
}
